### ISSUE TITLE
Reg ::  Running selected scenarios by tags in browserstack

### ISSUE THREAD

**Issue by mrsenzy** [ashwingonsalves/Cypress-Cucumber-Samples#1] opened 2021-03-04 20:22 UTC
How to Run selected scenarios by tags in browserstack ... currently it runs all scenarios referenced in test files in cypress.json

**Comment by david-dioses** [comment] 2021-04-08 21:33
I wanted to ask the same question, actually I have been able to run only those with the tags selected with these command line:

browserstack-cypress run --headed --env TAGS='@Heading' --sync

The problem is that even when just the ones with the expected tag are run, the other ones are also listed (as passed). If you enter to the detail it will show you that they were actually skipped.

I would like to know if there is a way that only those matching are listed in the run.

**Comment by ashwingonsalves** [comment] 2022-02-04 16:22
It has been a long time since I updated the repository.

@david-dioses thanks for sharing the command. @mrsenzy if not done already you can also try the example [here](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#ignoring-specific-scenarios-using-tags-when-executing-test-runner).

@david-dioses, the behaviour you are seeing on BrowserStack is similar to the report retrieved locally (on your machine). The main difference is with the ignored tests being marked passed on BrowserStack while locally it is marked as pending. I will be sharing this as a feedback with the BrowserStack Cypress team.

**Closed as completed** 2022-02-04 16:22 UTC
